# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Shrikant Keralapura
description: "Hi I'm Shrikant, and I'm a Technology leader.  This page contains my portfolio of interesting projects I've recently undertaken, with a strong emphasis on understanding the building blocks and what happens under-the-hood. Please visit my Github & LinkedIn pages by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: <span style="color:#f58506"> Portfolio of projects </span>
location: "Indianapolis, USA"
avatar_image: /img/profile_picture.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/shrikantkeralapura/" # Add your linkedln handle
github: "https://github.com/skeralapura"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/







